<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-11T16:05:06 CDT" name="Suite" finished-at="2021-06-11T16:05:29 CDT" duration-ms="22426">
    <groups>
    </groups>
    <test started-at="2021-06-11T16:05:06 CDT" name="Automation Test" finished-at="2021-06-11T16:05:29 CDT" duration-ms="22426">
      <class name="BaseTest.SampleTest">
        <test-method is-config="true" signature="BeforeTestMethod()[pri:0, instance:BaseTest.SampleTest@31e5415e]" started-at="2021-06-11T16:05:06 CDT" name="BeforeTestMethod" finished-at="2021-06-11T16:05:06 CDT" duration-ms="314" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTestMethod -->
        <test-method is-config="true" signature="BeforeMethodMethod(java.lang.String, java.lang.reflect.Method)[pri:0, instance:BaseTest.SampleTest@31e5415e]" started-at="2021-06-11T16:05:06 CDT" name="BeforeMethodMethod" finished-at="2021-06-11T16:05:15 CDT" duration-ms="8172" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void BaseTest.SampleTest.TestRunMethod()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethodMethod -->
        <test-method retried="true" signature="TestRunMethod()[pri:0, instance:BaseTest.SampleTest@31e5415e]" started-at="2021-06-11T16:05:15 CDT" name="TestRunMethod" finished-at="2021-06-11T16:05:17 CDT" duration-ms="2043" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page did not open expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page did not open expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at pageEvents.LoginPageEvent.LoginPgOpenOrNot(LoginPageEvent.java:16)
at BaseTest.SampleTest.TestRunMethod(SampleTest.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestRunMethod -->
        <test-method is-config="true" signature="AfterMethodMethod(org.testng.ITestResult)[pri:0, instance:BaseTest.SampleTest@31e5415e]" started-at="2021-06-11T16:05:17 CDT" name="AfterMethodMethod" finished-at="2021-06-11T16:05:18 CDT" duration-ms="1450" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TestRunMethod status=SKIP method=SampleTest.TestRunMethod()[pri:0, instance:BaseTest.SampleTest@31e5415e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethodMethod -->
        <test-method is-config="true" signature="BeforeMethodMethod(java.lang.String, java.lang.reflect.Method)[pri:0, instance:BaseTest.SampleTest@31e5415e]" started-at="2021-06-11T16:05:18 CDT" name="BeforeMethodMethod" finished-at="2021-06-11T16:05:25 CDT" duration-ms="6512" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void BaseTest.SampleTest.TestRunMethod()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethodMethod -->
        <test-method signature="TestRunMethod()[pri:0, instance:BaseTest.SampleTest@31e5415e]" started-at="2021-06-11T16:05:25 CDT" name="TestRunMethod" finished-at="2021-06-11T16:05:26 CDT" duration-ms="1838" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page did not open expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page did not open expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at pageEvents.LoginPageEvent.LoginPgOpenOrNot(LoginPageEvent.java:16)
at BaseTest.SampleTest.TestRunMethod(SampleTest.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestRunMethod -->
        <test-method is-config="true" signature="AfterMethodMethod(org.testng.ITestResult)[pri:0, instance:BaseTest.SampleTest@31e5415e]" started-at="2021-06-11T16:05:27 CDT" name="AfterMethodMethod" finished-at="2021-06-11T16:05:28 CDT" duration-ms="873" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TestRunMethod status=FAILURE method=SampleTest.TestRunMethod()[pri:0, instance:BaseTest.SampleTest@31e5415e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethodMethod -->
        <test-method is-config="true" signature="AfterTestMethod()[pri:0, instance:BaseTest.SampleTest@31e5415e]" started-at="2021-06-11T16:05:28 CDT" name="AfterTestMethod" finished-at="2021-06-11T16:05:29 CDT" duration-ms="365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTestMethod -->
      </class> <!-- BaseTest.SampleTest -->
    </test> <!-- Automation Test -->
  </suite> <!-- Suite -->
</testng-results>
